// Generated by CoffeeScript 1.7.1
(function() {
  angular.element(document).ready(function() {
    angular.module('myApp', []).controller('fileListcontrol', [
      '$scope', '$http', function($scope, $http) {
        $http({
          method: 'get',
          url: './pageinfo',
          catche: false
        }).success(function(data, status) {
            $scope.filelist = data.data;
            console.log($scope);
          });
      }
    ]);
    angular.bootstrap(document, ['myApp']);
  });

}).call(this);

//# sourceMappingURL=main.map
