// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    return $.ajax({
      url: "./pageinfo",
      type: "get",
      dataType: "json",
      success: function(data) {}
    });
  });

}).call(this);

//# sourceMappingURL=main.map
